- name: Configure new EC2 instance
  hosts: api_servers
  become: yes
  vars:
    username: api_user
    app_directory: /home/{{ username }}
    git_repo: "https://{{ github_token }}@github.com/behappyoo/sampleapp-api"  
  vars_files:
    - vault.yml  
  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ 'your_password' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Set permissions of .bashrc to 400 for api_user
      file:
        path: /home/api_user/.bashrc
        mode: '0600'
        owner: api_user
        group: api_user
      tags: permissions   
    
    - name: Install Node.js
      yum:
        name: nodejs
        state: present 
    
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Change root password
      command: echo "root:{{ root_password }}" | chpasswd

    - name: Switch to api_user and perform tasks
      become_user: api_user  # 여기서 api_user로 전환

      block:  # 블록 내의 모든 태스크는 api_user로 수행
        
        - name: Clone the API server code from GitHub  # GitHub에서 코드를 클론합니다.
          git:
            repo: "{{ git_repo }}"
            dest: "{{ app_directory }}"

        - name: Install npm dependencies
          command: npm install
          args:
            chdir: "{{ app_directory }}/sampleapp-api" 
        
        - name: Start the server
          command: node index.js
          args:
            chdir: "{{ app_directory }}/sampleapp-api"  # 서버 디렉토리에서 실행

    - name: Remove sudo privileges from ec2-user
      command: deluser ec2-user sudo