- name: Configure new EC2 instance
  hosts: Scaling-Group-Web
  remote_user: ec2-user
  become: yes 
  vars:
    app_directory: "/home/{{ webserveruser }}/webserver"
    git_repo: "https://github.com/behappyoo/sampleapp-frontend"
  vars_files:
    - vault.yml    
  tasks:
    - name: Create a new user
      user:
        name: "{{ webserveruser }}" 
        password: "{{ 'webserveruser_password' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Set permissions of .bashrc to 600 for user
      file:
        path: "/home/{{ webserveruser }}/.bashrc"
        mode: '0600'
        owner: "{{ webserveruser }}"
        group: "{{ webserveruser }}"
      tags: permissions    

    - name: Install Node.js
      yum:
        name: nodejs
        state: present 
    
    - name: Install Git
      yum:
        name: git
        state: present    

    - name: Change root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"

    - name: Switch user and perform tasks
      become_user: "{{ webserveruser }}"

      block:
        - name: Create webserver directory
          file:
            path: "/home/{{ webserveruser }}/webserver"  # 생성할 디렉토리 경로
            state: directory
            owner: "{{ webserveruser }}"
            group: "{{ webserveruser }}"
            mode: '0700'

        - name: Clone the API server code from GitHub
          git:
            repo: "{{ git_repo }}"
            dest: "{{ app_directory }}"

        - name: Install npm dependencies
          command: npm install
          args:
            chdir: "{{ app_directory }}"  # app_directory에서 명령어 실행   

        - name: Create .env file in project directory
          ansible.builtin.copy:
            dest: "{{ app_directory }}/.env"
            content: |
              VUE_APP_API_URL='{{ VUE_APP_API_URL }}'
            mode: '0600'    

        #- name: Add environment variables to .bashrc
        #  lineinfile:
        #    path: "/home/{{ webserveruser }}/.bashrc"
        #    create: yes
        #    line: "export {{ item.key }}={{ item.value }}"
        #  loop:
        #    - { key: 'VUE_APP_API_URL', value: '{{ VUE_APP_API_URL }}' }

        #- name: Reload bash to apply changes
        #  shell: source /home/{{ webserveruser }}/.bashrc
        #  args:
        #    executable: /bin/bash      
        
        - name: Start the server
          shell: nohup npm run serve > server.log 2>&1 &
          args:
            chdir: "{{ app_directory }}"
          async: 10  # 최대 10초 동안 실행
          poll: 0    # 즉시 다음 작업으로 넘어감