- name: Configure new EC2 instance
  hosts: web_servers
  become: yes 
  vars:
    app_directory: "/home/{{ webserveruser }}/webserver"
    git_repo: "https://{{ github_token }}@github.com/behappyoo/sampleapp-frontend"
  vars_files:
    - vault.yml    
  tasks:
    - name: Create a new user
      user:
        name: "{{ webserveruser }}"
        password: "{{ 'your_password' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Set permissions of .bashrc to 600 for user
      file:
        path: "/home/{{ webserveruser }}/.bashrc"
        mode: '0600'
        owner: "{{ webserveruser }}"
        group: "{{ webserveruser }}"
      tags: permissions    

    - name: Install Node.js
      yum:
        name: nodejs
        state: present 
    
    - name: Install Git
      yum:
        name: git
        state: present    

    - name: Change root password
      command: echo "root:{{ root_password }}" | chpasswd

    - name: Switch user and perform tasks
      become_user: "{{ webserveruser }}"  # 여기서 api_user로 전환

      block:  # 블록 내의 모든 태스크는 api_user로 수행
        - name: Create webserver directory
          file:
            path: "/home/{{ webserveruser }}/webserver"  # 생성할 디렉토리 경로
            state: directory
            owner: "{{ webserveruser }}"
            group: "{{ webserveruser }}"
            mode: '0700'

        - name: Clone the API server code from GitHub  # GitHub에서 코드를 클론합니다.
          git:
            repo: "{{ git_repo }}"
            dest: "{{ app_directory }}"

        - name: Install npm dependencies
          command: npm install
          args:
            chdir: "{{ app_directory }}/sampleapp-frontend"  # app_directory에서 명령어 실행   

        - name: Add environment variables to .bashrc
          lineinfile:
            path: "/home/{{ webserveruser }}/.bashrc"
            create: yes
            line: "export {{ item.key }}={{ item.value }}"
          loop:
            - { key: 'VUE_APP_API_URL', value: '{{ VUE_APP_API_URL }}' }

        - name: Reload bash to apply changes
          shell: source /home/{{ webserveruser }}/.bashrc
          args:
            executable: /bin/bash      
        
        - name: Start the server
          command: node index.js
          args:
            chdir: "{{ app_directory }}/sampleapp-frontend"  # 서버 디렉토리에서 실행

    - name: Remove sudo privileges from ec2-user
      command: deluser ec2-user sudo